--1- Destribute City Bonus across the branches in this city in equal quota.
SET SERVEROUTPUT ON
CREATE OR REPLACE FUNCTION DEST_CITY_BONUS(V_CITY_ID NUMBER)
RETURN NUMBER
IS
C_BONUS NUMBER(10);
V_COUN NUMBER(4);
V_BRANCH_BONUS NUMBER(10);
BEGIN
 SELECT  CITY_BONUS  INTO C_BONUS FROM CITIES
 WHERE CITY_ID = V_CITY_ID ;
 SELECT COUNT(CITY_ID) INTO V_COUN FROM BRANCHES WHERE CITY_ID = V_CITY_ID ;
 
 V_BRANCH_BONUS := C_BONUS/V_COUN ;
 RETURN V_BRANCH_BONUS ;
END;

CREATE OR REPLACE PROCEDURE UPDATE_BRANCHS_PROC(V_CITY_ID NUMBER , V_BONUS NUMBER)
IS
BEGIN
 UPDATE BRANCHES SET BRANCH_BONUS = V_BONUS WHERE CITY_ID = V_CITY_ID ;
END;

--2- Destibute the branch bonus across the employees work in this branch not in equal parts Mgrs take 50% Employees take 50% .
CREATE OR REPLACE FUNCTION EMP_BONUS_FUNC(V_BRANCH_ID NUMBER , V_EMP_POSITION VARCHAR2 ,V_BRANCH_BONUS NUMBER )
RETURN NUMBER
IS
V_EMP_BONUS NUMBER(10);
COUNT_EMP NUMBER(4);
BEGIN
    SELECT COUNT(*) INTO COUNT_EMP FROM BRANCH_EMPLOYEES 
    WHERE BRANCH_ID = V_BRANCH_ID  AND EMPLOYEE_POSITION = V_EMP_POSITION ;
    IF V_EMP_POSITION = 'MGR' THEN V_EMP_BONUS :=  V_BRANCH_BONUS * 0.5 / COUNT_EMP ;
    ELSE V_EMP_BONUS := V_BRANCH_BONUS * 0.5 / COUNT_EMP ;
    END IF ;
    RETURN V_EMP_BONUS ;
END;
CREATE OR REPLACE PROCEDURE UPDAET_EMP_BONUS_PROC(V_EMP_ID NUMBER , V_EMP_BONUS NUMBER)
IS 
BEGIN
UPDATE BRANCH_EMPLOYEES SET EMPLOYEE_BONUS = V_EMP_BONUS 
WHERE EMPLOYEE_ID = V_EMP_ID  ;
END ; 



