DECLARE   
         CURSOR DB_SEQ_CURSOR IS
              SELECT SEQUENCE_NAME
              FROM USER_SEQUENCES;
      
      CURSOR DB_TAB_CURSOR IS 
           SELECT T.TABLE_NAME , T.COLUMN_NAME FROM USER_TAB_COLUMNS T ,  USER_CONS_COLUMNS COL  , USER_CONSTRAINTS CON ,USER_OBJECTS O
           WHERE CON.CONSTRAINT_NAME = COL.CONSTRAINT_NAME AND 
           COL.COLUMN_NAME = T.COLUMN_NAME AND T.TABLE_NAME = O.OBJECT_NAME AND O.OBJECT_TYPE = 'TABLE' AND 
           T.DATA_TYPE = 'NUMBER' AND CON.CONSTRAINT_TYPE = 'P' ; 
            V_MAX_VALUE NUMBER(10); 
BEGIN
  FOR SEQ_RECORD IN DB_SEQ_CURSOR LOOP
  EXECUTE IMMEDIATE 'DROP SEQUENCE ' || SEQ_RECORD.SEQUENCE_NAME ;
  END LOOP;

   FOR TAB_RECORD IN DB_TAB_CURSOR LOOP
      EXECUTE IMMEDIATE 'SELECT MAX('|| TAB_RECORD.COLUMN_NAME ||') FROM ' || TAB_RECORD.TABLE_NAME INTO V_MAX_VALUE ;
      dbms_output.put_line(V_MAX_VALUE );
      EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || TAB_RECORD.TABLE_NAME ||'_SEQ ' || ' START WITH ' || (V_MAX_VALUE+1) || ' INCREMENT BY 1 ' ;
      
      EXECUTE IMMEDIATE 'CREATE OR REPLACE TRIGGER ' || TAB_RECORD.TABLE_NAME || '_TR 
             BEFORE INSERT ON ' || TAB_RECORD.TABLE_NAME || ' FOR EACH ROW 
             BEGIN 
             :NEW.' || TAB_RECORD.COLUMN_NAME || ':=' || TAB_RECORD.TABLE_NAME || '_SEQ.NEXTVAL ;
             END; ' ;
   END LOOP ;
END;